export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTHENTICATED = 'AUTHENTICATED';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const CLOSE_ALERT_TRUE = 'CLOSE_ALERT_TRUE';
export const CLOSE_ALERT_FALSE = 'CLOSE_ALERT_FALSE';
